"use server";

import { prisma } from '@/lib/prisma';

// Dynamic import for PDFKit to prevent loading during server startup
async function getPDFDocument() {
  const PDFDocument = (await import('pdfkit')).default;
  return PDFDocument;
}

export interface InvoiceData {
  orderId: string;
  orderNumber: string;
  customerName: string;
  customerEmail: string;
  orderDate: Date;
  items: Array<{
    name: string;
    variant: string;
    quantity: number;
    price: number;
    total: number;
  }>;
  subtotal: number;
  shipping: number;
  total: number;
  currency: string;
  shippingAddress: {
    name: string;
    addressLine1: string;
    addressLine2?: string | null;
    city: string;
    state?: string | null;
    postalCode: string;
    country: string;
  };
}

/**
 * Generate PDF Invoice
 */
export async function generateInvoicePDF(invoiceData: InvoiceData): Promise<Buffer> {
  return new Promise(async (resolve, reject) => {
    try {
      const PDFDocument = await getPDFDocument();
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc
        .fontSize(24)
        .fillColor('#2A9D9A')
        .text('FocusRobin', 50, 50)
        .fontSize(10)
        .fillColor('#666')
        .text('Invoice', 50, 80);

      // Invoice Details
      doc
        .fontSize(12)
        .fillColor('#000')
        .text(`Invoice Number: ${invoiceData.orderNumber}`, 400, 50)
        .text(`Date: ${invoiceData.orderDate.toLocaleDateString('en-US', { 
          year: 'numeric', 
          month: 'long', 
          day: 'numeric' 
        })}`, 400, 70)
        .text(`Order ID: ${invoiceData.orderId}`, 400, 90);

      // Customer Information
      doc
        .fontSize(14)
        .fillColor('#2A9D9A')
        .text('Bill To:', 50, 130)
        .fontSize(11)
        .fillColor('#000')
        .text(invoiceData.customerName, 50, 155)
        .text(invoiceData.customerEmail, 50, 170)
        .text(invoiceData.shippingAddress.addressLine1, 50, 185);
      
      if (invoiceData.shippingAddress.addressLine2) {
        doc.text(invoiceData.shippingAddress.addressLine2, 50, 200);
        let yPos = 215;
        doc.text(`${invoiceData.shippingAddress.city}, ${invoiceData.shippingAddress.postalCode}`, 50, yPos);
        yPos += 15;
        if (invoiceData.shippingAddress.state) {
          doc.text(invoiceData.shippingAddress.state, 50, yPos);
          yPos += 15;
        }
        doc.text(invoiceData.shippingAddress.country, 50, yPos);
      } else {
        let yPos = 200;
        doc.text(`${invoiceData.shippingAddress.city}, ${invoiceData.shippingAddress.postalCode}`, 50, yPos);
        yPos += 15;
        if (invoiceData.shippingAddress.state) {
          doc.text(invoiceData.shippingAddress.state, 50, yPos);
          yPos += 15;
        }
        doc.text(invoiceData.shippingAddress.country, 50, yPos);
      }

      // Items Table Header
      let yPos = 280;
      doc
        .fontSize(10)
        .fillColor('#2A9D9A')
        .text('Item', 50, yPos)
        .text('Quantity', 250, yPos)
        .text('Price', 350, yPos)
        .text('Total', 450, yPos);

      // Draw line under header
      doc
        .moveTo(50, yPos + 15)
        .lineTo(550, yPos + 15)
        .strokeColor('#2A9D9A')
        .lineWidth(1)
        .stroke();

      // Items
      yPos += 30;
      doc.fillColor('#000');
      invoiceData.items.forEach((item) => {
        doc
          .fontSize(10)
          .text(item.name, 50, yPos, { width: 180 })
          .text(item.variant, 50, yPos + 12, { width: 180 })
          .text(item.quantity.toString(), 250, yPos)
          .text(`${invoiceData.currency} ${item.price.toFixed(2)}`, 350, yPos)
          .text(`${invoiceData.currency} ${item.total.toFixed(2)}`, 450, yPos);
        yPos += 35;
      });

      // Totals
      yPos += 20;
      doc
        .fontSize(10)
        .text('Subtotal:', 350, yPos)
        .text(`${invoiceData.currency} ${invoiceData.subtotal.toFixed(2)}`, 450, yPos);
      yPos += 20;
      doc
        .text('Shipping:', 350, yPos)
        .text(`${invoiceData.currency} ${invoiceData.shipping.toFixed(2)}`, 450, yPos);
      yPos += 20;
      doc
        .fontSize(12)
        .fillColor('#2A9D9A')
        .text('Total:', 350, yPos)
        .text(`${invoiceData.currency} ${invoiceData.total.toFixed(2)}`, 450, yPos);

      // Footer
      doc
        .fontSize(8)
        .fillColor('#666')
        .text('Thank you for your purchase!', 50, 750, { align: 'center' })
        .text('This is an automated invoice generated by FocusRobin.', 50, 765, { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Get invoice data from order
 */
export async function getInvoiceDataFromOrder(orderId: string): Promise<InvoiceData | null> {
  try {
    const order = await prisma.order.findUnique({
      where: { id: orderId },
      include: {
        items: true,
        User: {
          select: {
            name: true,
            email: true,
          },
        },
      },
    });

    if (!order) {
      return null;
    }

    return {
      orderId: order.id,
      orderNumber: order.orderNumber,
      customerName: order.User?.name || order.shippingName || 'Customer',
      customerEmail: order.User?.email || 'customer@example.com',
      orderDate: order.createdAt,
      items: order.items.map((item) => ({
        name: item.productName,
        variant: item.variantName,
        quantity: item.quantity,
        price: Number(item.price),
        total: Number(item.total),
      })),
      subtotal: Number(order.subtotal),
      shipping: Number(order.shipping),
      total: Number(order.total),
      currency: order.currency,
      shippingAddress: {
        name: order.shippingName,
        addressLine1: order.shippingAddressLine1,
        addressLine2: order.shippingAddressLine2,
        city: order.shippingCity,
        state: order.shippingState,
        postalCode: order.shippingPostalCode,
        country: order.shippingCountry,
      },
    };
  } catch (error) {
    console.error('Error getting invoice data:', error);
    return null;
  }
}

